variables:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  ARROW_PRE_0_15_IPC_FORMAT: 1

stages:
  - test

test_circus:
  tags:
    - aiops-dispatching-ci
  script:
    - kill -9 $(ps -ef|grep entry  | grep -v grep | awk '{print $2}')  || true
    - kill -9 $(ps -ef|grep nosetests  | grep -v grep | awk '{print $2}')  || true
    - kill -9 $(ps -ef|grep circus  | grep -v grep | awk '{print $2}')  || true
    - kill -9 $(ps -ef|grep tox  | grep -v grep | awk '{print $2}')  || true
    - source /data/mapleleaf/venv/bin/activate
    - echo "do circus test!"
    - redis-cli flushall
    - mkdir -p working/logs || true
    - /data/mapleleaf/venv/bin/pip install -U tox
    - /data/mapleleaf/venv/bin/tox
    - kill -9 $(ps -ef|grep entry  | grep -v grep | awk '{print $2}')  || true
    - kill -9 $(ps -ef|grep nosetests  | grep -v grep | awk '{print $2}')  || true
    - kill -9 $(ps -ef|grep circus  | grep -v grep | awk '{print $2}')  || true
    - kill -9 $(ps -ef|grep tox  | grep -v grep | awk '{print $2}')  || true
